/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Negocio.PeajeO;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author HP
 */
public class PeajeEmpleado extends javax.swing.JFrame {

    FondoPanel fondo = new FondoPanel();
    /**
     * Creates new form TerminalEmpleado
     */
    public PeajeEmpleado() {
        this.setContentPane(fondo);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new FondoPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTFnombrePeaje = new javax.swing.JTextField();
        jTFcuidadPeaje = new javax.swing.JTextField();
        jTFubicacionPeaje = new javax.swing.JTextField();
        jTFnumeroCabinasPeaje = new javax.swing.JTextField();
        jTFcapacidadPeaje = new javax.swing.JTextField();
        jTFestadoPeaje = new javax.swing.JTextField();
        jTFfechaPeaje = new javax.swing.JTextField();
        jBnuevoRegistroPeaje = new javax.swing.JButton();
        jBaceptarRegistroPeaje = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel10 = new FondoPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAconsultaPeaje = new javax.swing.JTextArea();
        jTFnombreConsultaPeaje = new javax.swing.JTextField();
        jCBconsultasPeaje = new javax.swing.JComboBox<>();
        jBconsultarPeaje = new javax.swing.JButton();
        jBnuevoConsultaPeaje = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel11 = new FondoPanel();
        jLabel9 = new javax.swing.JLabel();
        jTFconsultaActualizarPeaje = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTFcuidadActualizarPeaje = new javax.swing.JTextField();
        jTFubicacionActualizarPeaje = new javax.swing.JTextField();
        jTFnumeroCabinasActualizarPeaje = new javax.swing.JTextField();
        jTFcapacidadActualizarPeaje = new javax.swing.JTextField();
        jTFestadoActualizarPeaje = new javax.swing.JTextField();
        jTFfechaActualizarPeaje = new javax.swing.JTextField();
        jBconsultarActualizarPeaje = new javax.swing.JButton();
        jBnuevoActualizarPeaje = new javax.swing.JButton();
        jBactualizarPeaje = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel3 = new FondoPanel();
        jLabel17 = new javax.swing.JLabel();
        jTFconsultarEliminarPeaje = new javax.swing.JTextField();
        jBconsultarEliminarPeaje = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTAconsultaEliminarPeaje = new javax.swing.JTextArea();
        jBnuevoEliminarPeaje = new javax.swing.JButton();
        jBeliminarPeaje = new javax.swing.JButton();
        jBregresar = new javax.swing.JButton();
        jBsalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre");

        jLabel2.setText("Cuidad");

        jLabel3.setText("Ubicación");

        jLabel4.setText("Numero de Cabinas");

        jLabel5.setText("Capacidad");

        jLabel6.setText("Estado ");

        jLabel7.setText("Fecha Actual");

        jTFnombrePeaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnombrePeajeActionPerformed(evt);
            }
        });

        jBnuevoRegistroPeaje.setText("Nuevo");
        jBnuevoRegistroPeaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevoRegistroPeajeActionPerformed(evt);
            }
        });

        jBaceptarRegistroPeaje.setText("Aceptar");
        jBaceptarRegistroPeaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBaceptarRegistroPeajeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(jLabel4))
                        .addGap(18, 59, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFnumeroCabinasPeaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFnombrePeaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFcuidadPeaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFubicacionPeaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBnuevoRegistroPeaje)
                        .addGap(114, 114, 114)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jTFfechaPeaje, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jTFestadoPeaje, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTFcapacidadPeaje, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jBaceptarRegistroPeaje)))
                .addGap(29, 29, 29))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTFcapacidadPeaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTFestadoPeaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTFfechaPeaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTFnombrePeaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTFcuidadPeaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTFubicacionPeaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTFnumeroCabinasPeaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(67, 67, 67)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBnuevoRegistroPeaje)
                    .addComponent(jBaceptarRegistroPeaje))
                .addContainerGap(163, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Registro", jPanel1);

        jLabel8.setText("Nombre ");

        jTAconsultaPeaje.setColumns(20);
        jTAconsultaPeaje.setRows(5);
        jTAconsultaPeaje.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta del Peaje"));
        jScrollPane1.setViewportView(jTAconsultaPeaje);

        jCBconsultasPeaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ubicación", "Cuidad", "Numero de Cabinas", "Estado", "Capacidad" }));
        jCBconsultasPeaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBconsultasPeajeActionPerformed(evt);
            }
        });

        jBconsultarPeaje.setText("Consultar");
        jBconsultarPeaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBconsultarPeajeActionPerformed(evt);
            }
        });

        jBnuevoConsultaPeaje.setText("Nuevo");
        jBnuevoConsultaPeaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevoConsultaPeajeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFnombreConsultaPeaje, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(jCBconsultasPeaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBnuevoConsultaPeaje)
                .addGap(46, 46, 46)
                .addComponent(jBconsultarPeaje)
                .addGap(198, 198, 198))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBconsultasPeaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFnombreConsultaPeaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBconsultarPeaje)
                    .addComponent(jBnuevoConsultaPeaje))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Consulta", jPanel2);

        jLabel9.setText("Nombre");

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de la Carretera"));

        jLabel10.setText("Cuidad");

        jLabel11.setText("Ubicación");

        jLabel12.setText("Numero de Cabinas");

        jLabel13.setText("Capacidad");

        jLabel14.setText("Estado");

        jLabel15.setText("Fecha");

        jTFcuidadActualizarPeaje.setEnabled(false);

        jTFubicacionActualizarPeaje.setEnabled(false);
        jTFubicacionActualizarPeaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFubicacionActualizarPeajeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTFnumeroCabinasActualizarPeaje, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFubicacionActualizarPeaje, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFcuidadActualizarPeaje, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFfechaActualizarPeaje, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFestadoActualizarPeaje, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFcapacidadActualizarPeaje, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13)
                    .addComponent(jTFcuidadActualizarPeaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFcapacidadActualizarPeaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14)
                    .addComponent(jTFubicacionActualizarPeaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFestadoActualizarPeaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15)
                    .addComponent(jTFnumeroCabinasActualizarPeaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFfechaActualizarPeaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jBconsultarActualizarPeaje.setText("Consultar");
        jBconsultarActualizarPeaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBconsultarActualizarPeajeActionPerformed(evt);
            }
        });

        jBnuevoActualizarPeaje.setText("Nuevo");
        jBnuevoActualizarPeaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevoActualizarPeajeActionPerformed(evt);
            }
        });

        jBactualizarPeaje.setText("Actualizar");
        jBactualizarPeaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBactualizarPeajeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTFconsultaActualizarPeaje, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBconsultarActualizarPeaje))
                            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jBnuevoActualizarPeaje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBactualizarPeaje)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFconsultaActualizarPeaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jBconsultarActualizarPeaje))
                .addGap(15, 15, 15)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBnuevoActualizarPeaje)
                    .addComponent(jBactualizarPeaje))
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Actualizar", jPanel6);

        jLabel17.setText("Nombre");

        jBconsultarEliminarPeaje.setText("Consultar");
        jBconsultarEliminarPeaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBconsultarEliminarPeajeActionPerformed(evt);
            }
        });

        jTAconsultaEliminarPeaje.setColumns(20);
        jTAconsultaEliminarPeaje.setRows(5);
        jTAconsultaEliminarPeaje.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de la Carretera"));
        jScrollPane2.setViewportView(jTAconsultaEliminarPeaje);

        jBnuevoEliminarPeaje.setText("Nuevo");
        jBnuevoEliminarPeaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevoEliminarPeajeActionPerformed(evt);
            }
        });

        jBeliminarPeaje.setText("Eliminar");
        jBeliminarPeaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeliminarPeajeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane2)
                .addGap(54, 54, 54))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addComponent(jBnuevoEliminarPeaje)
                .addGap(58, 58, 58)
                .addComponent(jBeliminarPeaje)
                .addGap(183, 183, 183))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFconsultarEliminarPeaje, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBconsultarEliminarPeaje)
                .addGap(100, 100, 100))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFconsultarEliminarPeaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jBconsultarEliminarPeaje))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBeliminarPeaje)
                    .addComponent(jBnuevoEliminarPeaje))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Eliminar", jPanel7);

        jBregresar.setText("Regresar");
        jBregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBregresarActionPerformed(evt);
            }
        });

        jBsalir.setText("Salir");
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBregresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 457, Short.MAX_VALUE)
                .addComponent(jBsalir)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBregresar)
                    .addComponent(jBsalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBregresarActionPerformed
        OpcionesEmpleadoAMT opciones = new OpcionesEmpleadoAMT();
        opciones.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jBregresarActionPerformed

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBsalirActionPerformed

    private void jTFnombrePeajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnombrePeajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFnombrePeajeActionPerformed

    private void jCBconsultasPeajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBconsultasPeajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBconsultasPeajeActionPerformed

    private void jBconsultarActualizarPeajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBconsultarActualizarPeajeActionPerformed
        PeajeO peajeConsulta = new PeajeO();
        peajeConsulta.buscarPorNombre(jTFconsultaActualizarPeaje.getText());
        
        jTFcuidadActualizarPeaje.setText(peajeConsulta.getCiudad());
        jTFubicacionActualizarPeaje.setText(peajeConsulta.getUbicacion());
        jTFnumeroCabinasActualizarPeaje.setText(""+peajeConsulta.getNumCabinas());
        jTFcapacidadActualizarPeaje.setText(""+peajeConsulta.getCapacidad());
        jTFestadoActualizarPeaje.setText(peajeConsulta.getEstado());
        jTFfechaActualizarPeaje.setText(peajeConsulta.getFechaEstado());
    }//GEN-LAST:event_jBconsultarActualizarPeajeActionPerformed

    private void jTFubicacionActualizarPeajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFubicacionActualizarPeajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFubicacionActualizarPeajeActionPerformed

    private void jBnuevoRegistroPeajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevoRegistroPeajeActionPerformed
        jTFnombrePeaje.setText("");
        jTFcuidadPeaje.setText("");
        jTFubicacionPeaje.setText("");
        jTFcapacidadPeaje.setText("");
        jTFnumeroCabinasPeaje.setText("");
        jTFestadoPeaje.setText("");
        jTFfechaPeaje.setText("");
    }//GEN-LAST:event_jBnuevoRegistroPeajeActionPerformed

    private void jBaceptarRegistroPeajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBaceptarRegistroPeajeActionPerformed
        PeajeO peaje = new PeajeO(
                jTFnombrePeaje.getText(),
                jTFcuidadPeaje.getText(),
                jTFubicacionPeaje.getText(),
                Integer.parseInt(jTFcapacidadPeaje.getText()),
                Integer.parseInt(jTFnumeroCabinasPeaje.getText()),
                jTFestadoPeaje.getText(),
                jTFfechaPeaje.getText());
        peaje.insertarEnBaseDeDatos();
    }//GEN-LAST:event_jBaceptarRegistroPeajeActionPerformed

    private void jBnuevoConsultaPeajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevoConsultaPeajeActionPerformed
        jTFnombreConsultaPeaje.setText("");
        jTAconsultaPeaje.setText("");
    }//GEN-LAST:event_jBnuevoConsultaPeajeActionPerformed

    private void jBconsultarPeajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBconsultarPeajeActionPerformed
        PeajeO peajeConsulta = new PeajeO();
        peajeConsulta.buscarPorNombre(jTFnombreConsultaPeaje.getText());
        String selecion = (String) jCBconsultasPeaje.getSelectedItem();
        jTAconsultaPeaje.setText(selecion);
        switch (selecion) {
            case "Ubicación":
                jTAconsultaPeaje.setText(peajeConsulta.getUbicacion());
                break;
            case "Cuidad":
                jTAconsultaPeaje.setText(peajeConsulta.getCiudad());
                break;
            case "Numero de Cabinas":
                jTAconsultaPeaje.setText(""+peajeConsulta.getNumCabinas());
                break;
            case "Estado":
                jTAconsultaPeaje.setText(""+peajeConsulta.getEstado());
                break;
            case "Capacidad":
                jTAconsultaPeaje.setText(""+peajeConsulta.getCapacidad());
                break;
        }
    }//GEN-LAST:event_jBconsultarPeajeActionPerformed

    private void jBnuevoActualizarPeajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevoActualizarPeajeActionPerformed
        jTFconsultaActualizarPeaje.setText("");
        jTFcuidadActualizarPeaje.setText("");
        jTFubicacionActualizarPeaje.setText("");
        jTFnumeroCabinasActualizarPeaje.setText("");
        jTFcapacidadActualizarPeaje.setText("");
        jTFestadoActualizarPeaje.setText("");
        jTFfechaActualizarPeaje.setText("");
    }//GEN-LAST:event_jBnuevoActualizarPeajeActionPerformed

    private void jBactualizarPeajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBactualizarPeajeActionPerformed
        PeajeO peajeAct = new PeajeO();
        peajeAct.actualizarPeaje(
                jTFconsultaActualizarPeaje.getText(),
                Integer.parseInt(jTFcapacidadActualizarPeaje.getText()),
                Integer.parseInt(jTFnumeroCabinasActualizarPeaje.getText()),
                jTFestadoActualizarPeaje.getText(),
                jTFfechaActualizarPeaje.getText());
    }//GEN-LAST:event_jBactualizarPeajeActionPerformed

    private void jBconsultarEliminarPeajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBconsultarEliminarPeajeActionPerformed
       PeajeO peajeEliminar = new PeajeO();
       peajeEliminar.buscarPorNombre(jTFconsultarEliminarPeaje.getText());
       jTAconsultaEliminarPeaje.setText(peajeEliminar.toString());
    }//GEN-LAST:event_jBconsultarEliminarPeajeActionPerformed

    private void jBnuevoEliminarPeajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevoEliminarPeajeActionPerformed
        jTFconsultarEliminarPeaje.setText("");
        jTAconsultaEliminarPeaje.setText("");
    }//GEN-LAST:event_jBnuevoEliminarPeajeActionPerformed

    private void jBeliminarPeajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeliminarPeajeActionPerformed
        PeajeO peajeEli = new PeajeO();
        peajeEli.eliminarPeaje(jTFconsultarEliminarPeaje.getText());
    }//GEN-LAST:event_jBeliminarPeajeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PeajeEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PeajeEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PeajeEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PeajeEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PeajeEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBaceptarRegistroPeaje;
    private javax.swing.JButton jBactualizarPeaje;
    private javax.swing.JButton jBconsultarActualizarPeaje;
    private javax.swing.JButton jBconsultarEliminarPeaje;
    private javax.swing.JButton jBconsultarPeaje;
    private javax.swing.JButton jBeliminarPeaje;
    private javax.swing.JButton jBnuevoActualizarPeaje;
    private javax.swing.JButton jBnuevoConsultaPeaje;
    private javax.swing.JButton jBnuevoEliminarPeaje;
    private javax.swing.JButton jBnuevoRegistroPeaje;
    private javax.swing.JButton jBregresar;
    private javax.swing.JButton jBsalir;
    private javax.swing.JComboBox<String> jCBconsultasPeaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTAconsultaEliminarPeaje;
    private javax.swing.JTextArea jTAconsultaPeaje;
    private javax.swing.JTextField jTFcapacidadActualizarPeaje;
    private javax.swing.JTextField jTFcapacidadPeaje;
    private javax.swing.JTextField jTFconsultaActualizarPeaje;
    private javax.swing.JTextField jTFconsultarEliminarPeaje;
    private javax.swing.JTextField jTFcuidadActualizarPeaje;
    private javax.swing.JTextField jTFcuidadPeaje;
    private javax.swing.JTextField jTFestadoActualizarPeaje;
    private javax.swing.JTextField jTFestadoPeaje;
    private javax.swing.JTextField jTFfechaActualizarPeaje;
    private javax.swing.JTextField jTFfechaPeaje;
    private javax.swing.JTextField jTFnombreConsultaPeaje;
    private javax.swing.JTextField jTFnombrePeaje;
    private javax.swing.JTextField jTFnumeroCabinasActualizarPeaje;
    private javax.swing.JTextField jTFnumeroCabinasPeaje;
    private javax.swing.JTextField jTFubicacionActualizarPeaje;
    private javax.swing.JTextField jTFubicacionPeaje;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

        class FondoPanel extends JPanel
    {
        private Image imagen;
        
        @Override
        public void paint(Graphics g)
        {
            imagen = new ImageIcon(getClass().getResource("/Imagenes/Carreteras.jpg")).getImage();
            g.drawImage(imagen, 0, 0,getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    
    }



}
